Repository OpenListTeam/OpenList, pull requests merged in 2025-08, with the labels that each got.

#624 feat(local): add directory size support
  drivers/local/benchmark_calculatedirsize_test.go
  drivers/local/driver.go
  drivers/local/meta.go
  drivers/local/util.go
Labels: enhancement

#1099 feat(server): add error page and status code
  server/common/common.go
  server/handles/archive.go
  server/handles/down.go
  server/middlewares/down.go
Labels: enhancement, go

#1045 feat(123_open): add `DirectLink` option
  drivers/123_open/driver.go
  drivers/123_open/meta.go
  drivers/123_open/types.go
  drivers/123_open/util.go
Labels: enhancement, go

#983 docs(contributing): update guidelines
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: 文档

#1170 fix(wopan): use fixed timezone for parsing time
  drivers/wopan/util.go
Labels: bug, go

#1180 fix(123open): change DirectLink type from 'boolean' to 'bool'
  drivers/123_open/meta.go
Labels: bug, go

#1185 fix(123open): get direct link
  drivers/123_open/driver.go
  drivers/123_open/types.go
  drivers/123_open/util.go
Labels: bug, go
